[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "npm run backend"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 